---
# executes versionlock delete command

# call setup.yaml
- name: setup
  include_tasks: setup.yaml

# delete
- name: "dnf versionlock delete"    # noqa no-changed-when
  command:
    cmd: "dnf versionlock delete {{ _spec }}" # noqa no-changed-when
    warn: false
  register: _cmdresult
  changed_when: "'Deleting versionlock for' in _cmdresult.stdout"

# display the result
# stdout echo
- name: Display versionlock delete output
  debug:
    msg: "{{ _cmdresult.stdout }}"

...
