---
# executes versionlock exclude command

# call setup.yaml
- name: setup
  include_tasks: setup.yaml

# exclude
- name: "dnf versionlock exclude"    # noqa no-changed-when
  command:
    cmd: "dnf versionlock exclude {{ _spec }}" # noqa no-changed-when
    warn: false
  register: _cmdresult
  changed_when: "'Adding exclude on' in _cmdresult.stdout"

# display the result
# stdout echo
- name: Display versionlock exclude output
  debug:
    msg: "{{ _cmdresult.stdout }}"

...
