---
- name: Converge
  hosts: all
  tasks:
    - name: "Include fedora_dnf_versionlock"
      include_role:
        name: "fedora_dnf_versionlock"
      vars:
        fdv_cmd: add
        fdv_package_spec: "kube???-1.20.*"
